# Configuration parameters of hand MNS20
# Tool: tool1
#
# Last modified: 28-Mar-2023
transmissions:
  j_wrist_rotation:
    type: "transmission_interface/SimpleTransmission"
    hardware_interface: "PositionJointInterface"
  j_wrist_exfle:
    type: "transmission_interface/SimpleTransmission"
    hardware_interface: "PositionJointInterface"
  j_wrist_ulra:
    type: "transmission_interface/SimpleTransmission"
    hardware_interface: "PositionJointInterface"
