# np.random seed
seed: 0

# Algorithm parameters
general:
  alogrithm: "PPO"
  log_dir: "logs/"
  log_interval: 10
  checkpoint_dir: "checkpoints/"
  dur_at_obj: 3.0 # Duration to be at the object once reached before terminating episode (in seconds)

# Learning parameters
hyper_params:
  num_episodes: 1000
  max_episode_steps: 10000
  step_size: 0.1 # seconds
  learning_rate: 0.005
  end_episode_points: 50.0 # Points to add at the end of the episode

# Camera configuration
visual_sensors:
  config_cameras:
    camera:
      point_cloud:
        setup: "hand" # "static" or "hand"
        optical_frame: "camera_depth_optical_frame"
        ref_frame: "palm"
        num_points: 256
        min_range: 0.5
        max_range: 1.5

  config_imagined:
    ref_frame: "palm"
    num_points: 256
    stl_package: "mia_hand_description" # Package where the STL files are located. Assumes they are under the folder /meshes/stl of this package
