# Joints Limits of hand MNS20
#
# Last modified: 28-Mar-2023
joint_limits:
  j_index_fle:
    min_position: -1.177
    max_position: 1.188
  j_little_fle:
    min_position: -1.177
    max_position: 1.188
  j_mrl_fle:
    min_position: -0.120
    max_position: 1.303
  j_ring_fle:
    min_position: -1.177
    max_position: 1.188
  j_thumb_fle:
    min_position: 0.029
    max_position: 1.313
  j_thumb_opp:
    min_position: -0.628
    max_position: 0.000
  j_wrist_rotation: # 80 deg sup, 70 pro
    min_position: -1.22173 # Pronation
    max_position: 1.39626 # Supination
  j_wrist_exfle: # 80 deg flex, 30 deg ext
    min_position: -0.523599 # Extension
    max_position: 1.39626 # Flex
  j_wrist_ulra: # 10 deg rad, 15 deg ulnar
    min_position: -0.174533 # Radial
    max_position: 0.261799 # Ulnar
  
