# Joints Limits of hand MNS20
#
# Last modified: 28-Mar-2023
joint_limits:
  j_index_fle:
    min_position: 0.0 # -1.177
    max_position: 1.188
  j_little_fle:
    min_position: -1.177
    max_position: 1.188
  j_mrl_fle:
    min_position: -0.120
    max_position: 1.303
  j_ring_fle:
    min_position: -1.177
    max_position: 1.188
  j_thumb_fle:
    min_position: 0.029
    max_position: 1.313
  j_thumb_opp:
    min_position: -0.628
    max_position: 0.000
  j_wrist_rot: # 90 deg sup, 90 pro
    min_position: -1.57079633 # Pronation
    max_position: 1.57079633 # Supination
  j_wrist_exfle: # 70 deg flex, 60 deg ext
    min_position: -1.04719755 # Extension
    max_position: 1.22173048 # Flex
  j_wrist_ulra: # 20 deg rad, 30 deg ulnar
    min_position: -0.34906585 # Radial
    max_position: 0.523598776 # Ulnar
  
