---
#---------------------------------------------------------------------
# Controllers v1.1
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Publish all joint states -----------------------------------
#---------------------------------------------------------------------

# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50
#   pid: { p: 100.0, i: 0.01, d: 3.0 }

#---------------------------------------------------------------------
# Effort- Controllers ---------------------------------------
#---------------------------------------------------------------------

j_wrist_rotation_eff_controller:
  type: effort_controllers/JointEffortController
  joint: j_wrist_rotation
  pid: { p: 100.0, i: 0.01, d: 0.1 }
j_wrist_exfle_eff_controller:
  type: effort_controllers/JointEffortController
  joint: j_wrist_exfle
  pid: { p: 100.0, i: 0.01, d: 0.1 }
j_wrist_ulra_eff_controller:
  type: effort_controllers/JointEffortController
  joint: j_wrist_ulra
  pid: { p: 100.0, i: 0.01, d: 0.1 }

#---------------------------------------------------------------------
# Effort-Position Controllers ---------------------------------------
#---------------------------------------------------------------------

j_wrist_rotation_eff_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_wrist_rotation
  pid:
    d: 0.005
    i: 0.001
    i_clamp: 5
    p: 1.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 3.0

j_wrist_exfle_eff_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_wrist_exfle
  pid:
    d: 0.005
    i: 0.001
    i_clamp: 0.4
    p: 1.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 3.0
j_wrist_ulra_eff_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_wrist_ulra
  pid:
    d: 0.005
    i: 0.1
    i_clamp: 0.05
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0

#---------------------------------------------------------------------
# Effort-Velocity Controllers -- NOT TUNED-----------------------------
#---------------------------------------------------------------------

j_wrist_rotation_eff_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_wrist_rotation
  pid:
    d: 0.005
    i: 0.001
    i_clamp: 5
    p: 1.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 3.0

j_wrist_exfle_eff_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_wrist_exfle
  pid:
    d: 0.005
    i: 0.001
    i_clamp: 0.4
    p: 1.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 3.0
j_wrist_ulra_eff_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_wrist_ulra
  pid:
    d: 0.005
    i: 0.1
    i_clamp: 0.05
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0

#------------------------------------------------------------------
# JointPosition Controllers ---------------------------------------
#---------------------------------------------------------------------

j_wrist_rotation_position_controller:
  type: position_controllers/JointPositionController
  joint: j_wrist_rotation

j_wrist_exfle_position_controller:
  type: position_controllers/JointPositionController
  joint: j_wrist_exfle

j_wrist_ulra_position_controller:
  type: position_controllers/JointPositionController
  joint: j_wrist_ulra

#------------------------------------------------------------------
# JointVelocity Controllers ---------------------------------------
#---------------------------------------------------------------------

j_wrist_rotation_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: j_wrist_rotation

j_wrist_exfle_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: j_wrist_exfle

j_wrist_ulra_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: j_wrist_ulra
